language: go
go:
- 1.x
sudo: false
before_script:
- go vet ./...
- go test -race ./...
script:
- go build -i -race -o bin/ephemeral-roles ephemeral-roles.go
before_deploy:
- zip -r ephemeral-roles.zip .
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  region: us-east-1
  access_key_id: AKIAITOP2BVV6ICBAOYQ
  secret_access_key:
      secure: "DRiNOccQlO6CXSaiMHWnuRnLfI4TUPtaQDB1sj49HDjUI3sT4sk53lLLpNaifPBCMOc9lcvtwdfrM8Q78OvV119fQcNPfcxj6U0oDz/U4jY3joyxl3JuFxagbEyYTv0zdQ/83c+eVd+/FGWwVYQmfFGx8J9rGCSeqR8wnplK1vOBjs/9mOflQSOuuJbUV7i5zVS23R2RPuk/WdmTTGJschr0VDpJwcb1mTfAVQ9Zashj87sCUrQb9yHo8w58KuJRNQks2bAgp9R5NUTdDRhCaV8JDzKAUAv5cxkL4qfmeIKG7Pp2juv9U265yiGCDrN89ll4xM6GWv89HGWzdbIE+wdwl07gIoEpyfx+WjlMUQNsf2s3KkuwOIGw6RFQ0Oz2xTgGzVgKD/ckvLGFkjCZy+OxbH5A8IdIsiMpBKi1qYlbWuG8HDArxUSLYqwzo9XIyf2JRSDDRA/3cpzxhFEsczrViqELg6+cIo+3ytTjj26433iBr26LHKVwKRErF111pa+5ajTR5WG7L2qbPb27gV6WauK4cGEgUMefRq/dQMgjEVvAwjpBC3MIjuOQvuR3Q+s75NfmNcrhvuWvA2efmA262I9u9UGMeS4molDAsq+hovsT7glNuKMxmwTehDwd6+ZHRQdHDU6Q/48P/rkyA6e49Gg/v1VZlnCYYQ3/8zM="
  zip_file: ephemeral-roles.zip
  app: ephemeral-roles
  env: ephemeral-roles
  bucket_name: ephemeral-roles
  wait-until-deployed: true
  on:
    repo: ewohltman/ephemeral-roles
    all_branches: true
